apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: ingress-nginx
  name: ingress-nginx-controller
  namespace: ingress-nginx
data:
  use-gzip: "true" # ENABLE GZIP COMPRESSION
  gzip-level: "6"
  gzip-types: "*" # SPECIFY MIME TYPES TO COMPRESS ("*" FOR ALL)
