apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-api

spec:
  replicas: 1

  template:
    spec:
      containers:
        - name: notification-api
          image: apetitoebusinesssolutions.azurecr.io/notification-api:latest

          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
          
          
