apiVersion: apps/v1
kind: Deployment
metadata:
  name: authorization-api

spec:
  replicas: 1

  template:
    spec:
      containers:
        - name: authorization-api
          image: apetitoebusinesssolutions.azurecr.io/meinapetito-authorization-api:latest

          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Staging
          
          
