apiVersion: v1
kind: Pod
metadata:
  name: aspnetapp
  labels:
    app: aspnetapp
spec:
  containers:
    - image: "mcr.microsoft.com/dotnet/core/samples:aspnetapp"
      name: aspnetapp-image
      ports:
        - containerPort: 80
          protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: aspnetapp
spec:
  selector:
    app: aspnetapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aspnetapp
  # nginx.ingress.kubernetes.io/use-regex: "true"
  # nginx.ingress.kubernetes.io/rewrite-target: /$2
  #   cert-manager.io/issuer: letsencrypt-staging-http-issuer
  #   cert-manager.io/acme-challenge-type: http01

spec:
  ingressClassName: nginx
  # tls:
  #   - hosts:
  #       - apagictest.westeurope.cloudapp.azure.com
  #     secretName: guestbook-secret-name

  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aspnetapp
                port:
                  number: 80
